### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by allenyhu** [tobybreckon/fire-detection-cnn#59]
**Describe the issue or your query**
Trying to run `python3 firenet.py models/test.mp4` gives me a `RuntimeError: dictionary changed size during iteration` error. 

**Computing Environment (please complete the following information):**
 - OS: macOS 10.15.5
 - Tensorflow Version:  1.15
 - OpenCV Version: 4.4.0.46

**Additional context**
I've installed `tensorflow==1.15` instead of `tensorflow-gpu==1.15` since I'm running on macOS. Not sure if that has been tested before. Thank you!

**Comment by allenyhu** [comment]
This is the stack trace:

Traceback (most recent call last):
  File "firenet.py", line 18, in <module>
    import tflearn
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/tflearn/__init__.py", line 4, in <module>
    from . import config
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/tflearn/config.py", line 3, in <module>
    import tensorflow as tf
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "/Users/allenhuang/venv/tf-1.1.5-gpu/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration

**Comment by allenyhu** [comment]
Actually, I found the issue with the default macOS Python3 installation. Here is a link to the fix in case anyone else is running into this issue: https://github.com/tensorflow/tensorflow/issues/33183#issuecomment-554701214
