### ISSUE TITLE
models/FireNet file not found

### ISSUE THREAD

**Issue by ProudInsanWadhwa** [tobybreckon/fire-detection-cnn#60]
Traceback (most recent call last):
  File "firenet.py", line 82, in <module>
    model.load(os.path.join("models/FireNet", "firenet"),weights_only=True)
  File "/home/proud/.local/lib/python3.8/site-packages/tflearn/models/dnn.py", line 302, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "/home/proud/.local/lib/python3.8/site-packages/tflearn/helpers/trainer.py", line 502, in restore
    self.restorer_trainvars.restore(self.session, model_file)
  File "/home/proud/.local/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1289, in restore
    if not checkpoint_management.checkpoint_exists_internal(checkpoint_prefix):
  File "/home/proud/.local/lib/python3.8/site-packages/tensorflow/python/training/checkpoint_management.py", line 383, in checkpoint_exists_internal
    if file_io.get_matching_files(pathname):
  File "/home/proud/.local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 350, in get_matching_files
    return get_matching_files_v2(filename)
  File "/home/proud/.local/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 408, in get_matching_files_v2
    for matching_filename in _pywrap_file_io.GetMatchingFiles(
tensorflow.python.framework.errors_impl.NotFoundError: /home/proud/Desktop/fire-detection-cnn-master/models/FireNet; No such file or directory

**Comment by tobybreckon** [comment]
You need to run the download script for the models (see instructions in README.md) and make sure the resulting models directory is at /home/proud/Desktop/fire-detection-cnn-master/models/
